### ISSUE TITLE
cidr should be referenced as cidr_block

### ISSUE THREAD

**Issue by joewennechuk** [terraform-community-modules/tf_aws_vpc_only#3]
I have been playing with this, and it seems that best practice is to use the same variable names for inputs as aws outputs to avoid confusion. this module is using cidr as the input but aws outputs cidr_block am I missing something? Is there a reason why cidr is used and I just don't understand?

**Comment by antonbabenko** [comment]
You are absolutely correct. This has been done without proper thinking. There are no plans to change this in this module though unless somebody wants to submit a PR.
